---
- name: Deploy webserver on VM1 and VM2
  hosts: webservers
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create custom web page
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <body>
          <h1>Hello World from SJSU-{{ inventory_hostname[-1] }}</h1>
          </body>
          </html>

    - name: Change Apache port to 8080
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80'
        line: 'Listen 8080'
        state: present

    - name: Change Apache virtual host port to 8080
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: '^<VirtualHost \*:80>'
        line: '<VirtualHost *:8080>'
        state: present

    - name: Restart Apache service
      service:
        name: apache2
        state: restarted